identifier: yaw-kb
name: yaw-kb
type: keyboard
url: https://github.com/KiWeng/yaw-kb
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio